= 07 Idziemy na produkcj

== Tematy omawiane w tej czci:

* Monitoring
- zobacz: _Demo u偶ycia Metryk_
* Testy w procesie CI/CD
* Testy regresji
* Testowanie na produkcji
* Wydania vs. wdro偶enia
- zobacz: _Demo Feature Toggles_

== Uruchamianie aplikacji i test贸w

W tej lekcji wykorzystamy kontenery z nastpujcymi rzeczami:

 - fraud_verifier - aplikacja do weryfikacji os贸b
 - loan_orders - aplikacja do przyznawania po偶yczek
 - MongoDB - baza dokumentowa wykorzystywana przez loan_orders
 - Zipkin - narzdzie do Distributed Tracingu
 - Prometheus - narzdzie do zbierania metryk
 - Grafana - narzdzie do wirtualizacji zebranych metryk przez Prometheusa (i potencjalnie z wielu innych 藕r贸de)

Aby to wszystko uruchomi, przejd藕 do katalogu i wywoaj docker-compose:

```
cd 07-going-to-production
docker-compose up --build
```

== Demo Feature Toggles
1) Wywoaj polecenie `curl -H 'Content-type: application/json' -X POST http://localhost:9091/orders -d '@loanOrder.json'`

2) Nastpnie korzystajc ze zwr贸conego IDka, zapytaj o status - na przykad: `curl -H 'Content-type: application/json' http://localhost:9091/orders/5fa6b6f2e85ca33165d459ec`. Status powien by VERIFIED.

3) Mamy jeden feature toggle nazwany NEW_VERIFICATION `fraud_verifier.feature_toggles.features.Feature` kt贸ry steruje wczeniem (lub nie) dodatkowej weryfikacji - `fraud_verifier.customer.verification.new_type_of_verification.NewTypeOfVerification`.

4) Stan feature toggle'a jest zapisany w bazie danych SQLite w pliku (model `fraud_verifier.feature_toggles.model.FeatureModel`)

5) implementacja wykorzystuje go w rodku `fraud_verifier.customer.customer_verifier.CustomerVerifier.verify` poprzez `FeatureManager`'a kt贸ry po prostu czyta warto z bazy

6) Przestaw warto korzystajc z doczonego Flask-Admina (http://127.0.0.1:9090/admin/featuremodel/) i wykonaj ponownie 偶danie z pierwszego punktu - zobaczysz, 偶e zachowanie aplikacji si zmienia

7)  to demonstruje zasad dziaania feature toggle's i prosty spos贸b osignicia ich we Flasku/ka偶dym innym projekcie Pythonowym. Je偶eli u偶ywasz Django, warto sprawdzi dedykowan bibliotek, jak Django-Waffle

UWAGA: Na potrzeby demo korzystamy z bazy danych w pliku .sqlite - oczywicie w rodowisku produkcyjnym konfiguracja bdzie trzymana raczej w tej samej bazie, z kt贸rej korzysta aplikacja. Ponadto dostp do interfejsu administratora Flask-Admin nie jest chroniony, podczas gdy na produkcji zazwyczaj dostp do takiej konsoli bdziemy chcieli nada wycznie osobom z odpowiednimi uprawnieniami.

== Demo Distributed Tracing z Zipkinem
1) Majc uruchomion aplikacj i wszystkie zale偶noci, pu kilka 偶da, np. jak w punkcie 1. czci o Feature Toggles

2) Nastpnie otw贸rz GUI Zipkina: http://localhost:9411/zipkin/ i wcinij przycisk `Run Query`

3) Zobaczysz jak Twoje 偶dania przepyway przez serwisy i ile czasu spdziy w ka偶dym z nich. W ten spos贸b mo偶na weryfikowa jakie operacje byy wykonywane w kt贸rych serwisach, ile trway, i kt贸re z nich powodoway najwiksze op贸藕nienie.

4) Przejd藕 tez na zakadk _Dependencies_ i zobacz jak zwizualizowany zosta przepyw danych pomidzy serwisami

5)  W przykadzie u偶ywamy flask_zipkin korzystajcej pod spodem z py_zipkin. Automatycznie wpina si w 偶dania Flaska. Rcznie dodalimy te偶 odpowiednie nag贸wki w `loan_orders.fraud.client.verify_customer` by kolejno wywoany serwis wiedzia, 偶e jest czci wikszego acucha wywoa, co pozwala nam adnie ledzi cay przebieg procesu

6)  cay trud dodawania _distributed tracing_ do Twojej aplikacji to odpowiednia instrumentacja. Warto rozwa偶y te偶 komercyjne narzdzia, jak NewRelic czy DataDog.


== Demo u偶ycia metryk
1) Po wykonaniu kilku 偶da (np. z punktu 1. czci o Feature Toggles) otw贸rz adres http://localhost:9090/metrics by zobaczy wystawione metryki z aplikacji `fraud-verifier` (zobacz `fraud_verifier/\_\_init\_\_.py` i `fraud_verifier.metrics`)

2) Stworzylimy jedn wasn metryk `fraud_verifier.metrics.verify_customer_timer` do zliczania czasu spdzonego na weryfikacji i zaaplikowalimy j na `fraud_verifier.customer.customer_verifier.CustomerVerifier.verify` jako dekorator

3)  Pythonowy klient Prometheusa wrzuca _out-of-the-box_ par metryk dotyczcych garbage collectora. Flaskowe rozszerzenie `prometheus_flask_exporter` dodatkowo dostarcza nieco informacji o naszych 偶daniach.

== Demo dashboard贸w do metryk w Grafanie

Wartoci dodanych przez siebie metryk mo偶esz agregowa w Prometheusie i tworzy dla nich dashboardy w Grafanie.

1) Wykonaj troch zapyta opisanych w sekcji "Demo Feature Toggles"

2) W przegldarce uruchom Prometheusa pod `http://localhost:9100`. Mo偶esz przeglda metryki i tworzy do nich grafy

3) Otw贸rz Grafan w przegldarce `http://localhost:3000/` i zaloguj si u偶ywajc loginu i hasa 'admin'. Na stronie g贸wnej znajdziesz linki do 2 przykadowych dashboard贸w. Jeden z nich wykorzystuje metryk, kt贸r dodalimy w kodzie. Mo偶esz tworzy dashboardy dla dodanych przez siebie metryk.
